
-- 1. Total Orders Completed on 18th March 2023

SELECT COUNT(*) AS total_orders
FROM SALES
WHERE Date = '2023-03-18';

-- 2. Total Orders Completed on 18th March 2023 by ‘John Doe’

SELECT COUNT(*) AS total_orders_by_john_doe
FROM SALES S
JOIN CUSTOMERS C ON S.Customer_id = C.Customer_id
WHERE S.Date = '2023-03-18'
  AND C.First_name = 'John'
  AND C.Last_name = 'Doe';

-- 3. Total Customers Purchased in January 2023 and Average Amount Spent Per Customer

SELECT COUNT(DISTINCT Customer_id) AS total_customers,
       AVG(Total_Revenue) AS avg_spent_per_customer
FROM (
    SELECT Customer_id, SUM(Revenue) AS Total_Revenue
    FROM SALES
    WHERE Date BETWEEN '2023-01-01' AND '2023-01-31'
    GROUP BY Customer_id
) AS Customer_Revenue;

-- 4. Departments Generating Less Than $600 in 2022

SELECT COUNT(DISTINCT Customer_id) AS total_customers,
       AVG(Total_Revenue) AS avg_spent_per_customer
FROM (
    SELECT Customer_id, SUM(Revenue) AS Total_Revenue
    FROM SALES
    WHERE Date BETWEEN '2023-01-01' AND '2023-01-31'
    GROUP BY Customer_id
) AS Customer_Revenue;

-- 5. Most and Least Revenue Generated by an Order

SELECT MAX(Revenue) AS max_revenue, MIN(Revenue) AS min_revenue
FROM SALES;

-- 6. Orders in the Most Lucrative Order

WITH LucrativeOrder AS (
    SELECT Order_id, SUM(Revenue) AS Total_Revenue
    FROM SALES
    GROUP BY Order_id
    ORDER BY Total_Revenue DESC
    LIMIT 1
)
SELECT S.*
FROM SALES S
JOIN LucrativeOrder L ON S.Order_id = L.Order_id;

